/*
Read first and last name of the clients, which do not order any product
*/
SELECT C.FirstName, C.LastName
FROM SalesLT.Customer AS C
LEFT OUTER JOIN SalesLT.SalesOrderHeader AS OH
	ON OH.CustomerID=C.CustomerID
WHERE OH.SalesOrderID IS NULL
;

/*
OUTPUTS:
	FirstName                                          LastName
	-------------------------------------------------- --------------------------------------------------
	Orlando                                            Gee
	Keith                                              Harris
	Donna                                              Carreras
	Janet                                              Gates
	Lucy                                               Harrington
	Rosmarie                                           Carroll
	Dominic                                            Gash
	Kathleen                                           Garza
	Katherine                                          Harding
	Johnny                                             Caprio
	Christopher                                        Beck
	David                                              Liu
	John                                               Beaver
	Jean                                               Handley
	Jinghao                                            Liu
	Linda                                              Burnett
	Kerim                                              Hanif
	Kevin                                              Liu
	Donald                                             Blanton
	Jackie                                             Blackwell
	Bryan                                              Hamilton
	Todd                                               Logan
	Barbara                                            German
	Jim                                                Geist
	Betty                                              Haines
	Sharon                                             Looney
	Darren                                             Gehring
	Erin                                               Hagens
	Jeremy                                             Los
	Elsa                                               Leavitt
	David                                              Lawrence
	Hattie                                             Haemon
	Anita                                              Lucerne
	Rebecca                                            Laszlo
	Eric                                               Lang
	Brian                                              Groth
	Judy                                               Lundahl
	Peter                                              Kurniawan
	Douglas                                            Groncki
	Sean                                               Lunt
	Jeffrey                                            Kurtz
	Vamsi                                              Kuppa
	Jane                                               Greer
	Alexander                                          Deborde
	Deepak                                             Kumar
	Margaret                                           Krupka
	Christopher                                        Bright
	Aidan                                              Delaney
	James                                              Krow
	Michael                                            Brundage
	Stefan                                             Delmarco
	Mitch                                              Kennedy
	James                                              Kramer
	Eric                                               Brumfield
	Della                                              Demott Jr
	Pamala                                             Kotc
	Joy                                                Koski
	Jovita                                             Carmody
	Prashanth                                          Desai
	Scott                                              Konersmann
	Jane                                               Carmichael
	Bonnie                                             Lepro
	Eugene                                             Kogan
	Kirk                                               King
	William                                            Conner
	Linda                                              Leste
	Andrea                                             Thomsen
	Daniel                                             Thompson
	Kendra                                             Thompson
	Scott                                              Colvin
	Elsie                                              Lewin
	Donald                                             Thompson
	John                                               Colon
	George                                             Li
	Yale                                               Li
	Phyllis                                            Thomas
	Pat                                                Coleman
	Yuhong                                             Li
	Joseph                                             Lique
	Judy                                               Thames
	Connie                                             Coffman
	Paulo                                              Lisboa
	Vanessa                                            Tench
	Teanna                                             Cobb
	Michael                                            Graff
	Derek                                              Graham
	Gytis                                              Barzdukas
	Jane                                               Clayton
	Jon                                                Grande
	Ted                                                Bremer
	Richard                                            Bready
	Alice                                              Clark
	Alan                                               Brewer
	Cornelius                                          Brandon
	Jill                                               Christie
	Walter                                             Brian
	Carlton                                            Carlisle
	Joseph                                             Castellucio
	Lester                                             Bowman
	Brigid                                             Cavendish
	Andrew                                             Cencini
	Cindy                                              Dodd
	Randall                                            Boseman
	Stacey                                             Cereghino
	Blaine                                             Dockter
	Luis                                               Bonifaz
	Brenda                                             Diaz
	Gabriele                                           Dickmann
	Rudolph                                            Dillon
	Michael                                            Bohling
	Dick                                               Dievendorff
	Nicky                                              Chesnut
	Michael                                            Lee
	Stanley                                            Alan
	Yao-Qiang                                          Cheng
	Marjorie                                           Lee
	Sandeep                                            Kaliyath
	Pei                                                Chow
	Frank                                              Campbell
	Mark                                               Lee
	Sandra                                             Kitt
	Hao                                                Chen
	Jolie                                              Lenehan
	Diane                                              Krane
	Payton                                             Benson
	Roger                                              Lengel
	Peggy                                              Justice
	Edna                                               Benson
	A.                                                 Leonetti
	Jean                                               Jordan
	Ido                                                Ben-Sachar
	Frank                                              Martˇnez
	Steve                                              Masters
	Robert                                             Jones
	Josh                                               Barnhill
	Jennifer                                           Maxham
	Chris                                              Maxwell
	David                                              Johnson
	Brian                                              Johnson
	Robert                                             Brown
	Sandra                                             Maynard
	Barry                                              Johnson
	Joyce                                              Jarvis
	Vance                                              Johns
	Robin                                              McGuigan
	Danielle                                           Johnson
	David                                              Jaffe
	Mary                                               Alexander
	Lola                                               McCarthy
	Mary                                               Browning
	Jodan                                              Jacobson
	Jane                                               McCarty
	Jessie                                             Valerio
	Eric                                               Jacobsen
	Bronson                                            Jacobs
	James                                              McCoy
	Esther                                             Valle
	Denean                                             Ison
	Erik                                               Ismert
	Robert                                             Bernacchi
	Sunil                                              Uppal
	Richard                                            Irwin
	Matthias                                           Berndt
	Sairaj                                             Uddin
	Lucio                                              Iallo
	Beth                                               Inghram
	Timothy                                            Burnett
	Phyllis                                            Tuffield
	Richard                                            Byham
	Jared                                              Bustamante
	Henry                                              Campen
	Christie                                           Trujillo
	Janet                                              Gilliat
	Chris                                              Cannon
	Michael John                                       Troyer
	Guy                                                Gilbert
	Frances                                            Giglio
	Suzana De Abreu                                    Canuto
	Billy                                              Trent
	Leo                                                Giakoumakis
	Grant                                              Culbertson
	Robert                                             Barker
	Gabriel                                            Bockenkamp
	Scott                                              Culp
	Wayne                                              Banack
	Michael                                            Blythe
	Conor                                              Cunningham
	Alberto                                            Baltazar
	Joseph                                             Mitzner
	Robert                                             Mitosinka
	Thierry                                            D'Hers
	Daniel                                             Blanco
	Linda                                              Mitchell
	Stephen                                            Ayers
	Neva                                               Mitchell
	Megan                                              Davis
	John                                               Arthur
	Frank                                              Miller
	Alvaro                                             De Matos Miranda Filho
	Thomas                                             Armstrong
	Dylan                                              Miller
	Ben                                                Miller
	Jacob                                              Dean
	Ann                                                Beebe
	Matthew                                            Miller
	Jo                                                 Brown
	Virginia                                           Miller
	Scott                                              Gode
	Caroline                                           Vicknair
	Robert                                             Vessa
	Andreas                                            Berglund
	Mete                                               Goktepe
	Wanda                                              Vernon
	Dora                                               Verdad
	John                                               Berger
	Brian                                              Goldstein
	Raja                                               Venugopal
	Patricia                                           Vasquez
	Karren                                             Burkhardt
	Abigail                                            Gonzalez
	Ranjit                                             Varkey Chudukatil
	Ingrid                                             Burkhardt
	Oscar                                              Alpuerto
	Gary                                               Vargas
	Shane                                              Kim
	Joan                                               Campbell
	Maxwell                                            Amland
	Joe                                                Kim
	Ramona                                             Antrim
	Karan                                              Khanna
	Sharon                                             Crow
	Chris                                              Ashton
	Imtiaz                                             Khan
	Jack                                               Creasey
	Teresa                                             Atkinson
	Tammy                                              Khan
	Elizabeth                                          Keyser
	Bruno                                              Costa Da Silva
	Katherine                                          Swan
	Mary                                               Kesslep
	Marlin                                             Coriell
	Kevin                                              Kennedy
	Eva                                                Corets
	Julie                                              Taft-Rider
	Robert                                             Kelly
	Scott                                              Cooper
	Clarence                                           Tatman
	John                                               Kelly
	Victor                                             Kelley
	Dorothy                                            Contreras
	Mike                                               Taylor
	Bonnie                                             Kearney
	June                                               Brunner
	Sandeep                                            Katyal
	Shirley                                            Bruner
	Chad                                               Tedford
	Peter                                              Houston
	Tom                                                Johnston
	Marian                                             Berch
	Juanita                                            Holman
	Eddie                                              Holmes
	Robert                                             Avalos
	Alexander                                          Berger
	Jean                                               Holloway
	Greg                                               Chapman
	Angela                                             Barbariol
	Ruth                                               Choin
	Lee                                                Chapla
	Darrell                                            Banks
	Anthony                                            Chor
	Forrest                                            Chandler
	Eli                                                Bowen
	Stephen                                            Jiang
	Dirk                                               Bruno
	Gustavo                                            Camargo
	Douglas                                            Baldwin
	Lindsey                                            Camacho
	James                                              Bailey
	Carol                                              Elliott
	Barbara                                            Calone
	Megan                                              Burke
	Cory                                               Booth
	Shannon                                            Elliott
	Jauna                                              Elson
	Janaina Barreiro Gambaro                           Bueno
	Shaun                                              Beasley
	John                                               Emory
	Olga                                               Trau
	Jon                                                Ganio
	Gail                                               Erickson
	James                                              Tran
	Michael                                            Galos
	Mark                                               Erickson
	Martha                                             Espinoza
	Glenn                                              Track
	Bob                                                Gage
	Janeth                                             Esteves
	Paul                                               Fulton
	Twanna                                             Evans
	Delia                                              Toone
	John                                               Ford
	Ann                                                Evans
	Kay                                                Krane
	Mihail                                             Frintu
	John                                               Evans
	Ruby Sue                                           Styles
	Lori                                               Kane
	Susan                                              French
	Gary                                               Suess
	Ruth                                               Suffin
	Margaret                                           Smith
	Dorothy                                            Fox
	Elizabeth                                          Sullivan
	Frances                                            Adams
	Garth                                              Fort
	Michael                                            Sullivan
	Marcia                                             Sultan
	Amy                                                Alberts
	Kelly                                              Focht
	Krishna                                            Sunkammurali
	Mae                                                Black
	Brad                                               Sutton
	François                                           Ferrier
	Mary                                               Bishop
	Martin                                             Svoboda
	Robert                                             Ahlering
	Jimmy                                              Bischoff
	Abraham                                            Swearengin
	Ryan                                               Calafato
	Dragan                                             Tomic
	Thomas                                             Michaels
	Mari                                               Caldwell
	Mary                                               Gimmi
	David                                              Givens
	Diane                                              Tibbott
	Helen                                              Meyer
	Jeanie                                             Glenn
	Diane                                              Glimp
	Yuping                                             Tian
	Stephen                                            Mew
	John                                               Brooks
	Willie                                             Brooks
	Andrew                                             Kobylinski
	R. Morgan                                          Mendoza
	Jay                                                Adams
	Christian                                          Kleinerman
	Anton                                              Kirilov
	Gladys                                             Mendiola
	Raquel                                             Mello
	Samuel                                             Agcaoili
	Tim                                                Kim
	Nancy                                              McPhearson
	Nkenge                                             McLin
	Paul                                               Alcorn
	Marvin                                             Allen
	Yvonne                                             McKay
	Sean                                               Jacobson
	Michelle                                           Alexander
	Richard                                            Bentley
	Curtis                                             Howard
	Cecil                                              Allison
	Gregory                                            Alderson
	Janice                                             Hows
	George                                             Huckaby
	Carolyn                                            Farino
	Kim                                                Abercrombie
	Joshua                                             Huff
	Geri                                               Farrell
	Catherine                                          Abel
	Laura                                              Steele
	Shanay                                             Steelman
	Rhoda                                              Finley
	Pat                                                Chambers
	Stefano                                            Stefani
	Alan                                               Steiner
	Kathie                                             Flood
	Bob                                                Hodges
	Derik                                              Stenerson
	Raul                                               Casts
	Holly                                              Holt
	Vassar                                             Stern
	Wathalee                                           Steuber
	Matthew                                            Cavallari
	Helge                                              Hoeing
	Alice                                              Steiner
	Steven                                             Brown
	David                                              Hodgson
	Liza Marie                                         Stevens
	Jim                                                Stewart
	Arlene                                             Huff
	Matthew                                            Hunter
	Matthew                                            Hink
	Robert                                             Stotka
	Phyllis                                            Huntsman
	Mike                                               Hines
	Kayla                                              Stotler
	Lawrence                                           Hurkett
	Ryan                                               Ihrig
	Andrew                                             Hill
	Robert                                             Lyeba
	Roger                                              Van Houten
	Robert                                             Lyon
	Rose                                               Vandenouer
	Denise                                             Maccietto
	Gregory                                            Vanderbout
	Ronald                                             Heymsfield
	Scott                                              MacDonald
	Michael                                            Vanderhyde
	Cheryl                                             Herring
	Walter                                             Mays
	Margaret                                           Vanderkamp
	Kara                                               Vanderlinden
	Jésus                                              Hernandez
	Irene                                              Hernandez
	Ajay                                               Manchepalli
	Nieves                                             Vargas
	Kari                                               Hensien
	Tomas                                              Manzanares
	Kathy                                              Marcovecchio
	Patricia                                           Doyle
	Valerie                                            Hendricks
	Jill                                               Markwood
	Gerald                                             Drury
	John                                               Hanson
	Melissa                                            Marple
	Cecelia                                            Marshall
	Reuben                                             D'sa
	Brenda                                             Heaney
	Linda                                              Martin
	James                                              Haugh
	Sandra                                             Martinez
	Bev                                                Desalvo
	Bart                                               Duncan
	Ann                                                Hass
	Rob                                                Caron
	Maciej                                             Dusza
	Roger                                              Harui
	Andy                                               Carothers
	Linda                                              Ecoffey
	Kim                                                Abercrombie
	Frances                                            Adams
	Margaret                                           Smith
	Jay                                                Adams
	Samuel                                             Agcaoili
	Robert                                             Ahlering
	François                                           Ferrier
	Amy                                                Alberts
	Paul                                               Alcorn
	Gregory                                            Alderson
	Michelle                                           Alexander
	Sean                                               Jacobson
	Marvin                                             Allen
	Cecil                                              Allison
	Oscar                                              Alpuerto
	Maxwell                                            Amland
	Ramona                                             Antrim
	Tom                                                Johnston
	Thomas                                             Armstrong
	John                                               Arthur
	Chris                                              Ashton
	Teresa                                             Atkinson
	Robert                                             Avalos
	Stephen                                            Ayers
	Daniel                                             Blanco
	James                                              Bailey
	Douglas                                            Baldwin
	Wayne                                              Banack
	Robert                                             Barker
	Josh                                               Barnhill
	Gytis                                              Barzdukas
	Shaun                                              Beasley
	John                                               Beaver
	Ann                                                Beebe
	Stanley                                            Alan
	Edna                                               Benson
	Payton                                             Benson
	Alexander                                          Berger
	John                                               Berger
	Robert                                             Bernacchi
	Matthias                                           Berndt
	Steven                                             Brown
	Jimmy                                              Bischoff
	Mae                                                Black
	Jackie                                             Blackwell
	Linda                                              Burnett
	Michael                                            Blythe
	Gabriel                                            Bockenkamp
	Luis                                               Bonifaz
	Randall                                            Boseman
	Eli                                                Bowen
	Lester                                             Bowman
	Cornelius                                          Brandon
	Richard                                            Bready
	Ted                                                Bremer
	Alan                                               Brewer
	Christopher                                        Bright
	John                                               Brooks
	Willie                                             Brooks
	Jo                                                 Brown
	Robert                                             Brown
	Mary                                               Browning
	Eric                                               Brumfield
	Michael                                            Brundage
	Shirley                                            Bruner
	June                                               Brunner
	Dirk                                               Bruno
	Janaina Barreiro Gambaro                           Bueno
	Megan                                              Burke
	Karren                                             Burkhardt
	Timothy                                            Burnett
	Jared                                              Bustamante
	Ryan                                               Calafato
	Mari                                               Caldwell
	Barbara                                            Calone
	Lindsey                                            Camacho
	Gustavo                                            Camargo
	Joan                                               Campbell
	Henry                                              Campen
	Chris                                              Cannon
	Suzana De Abreu                                    Canuto
	Johnny                                             Caprio
	Carlton                                            Carlisle
	Jane                                               Carmichael
	Jovita                                             Carmody
	Rob                                                Caron
	Andy                                               Carothers
	Donna                                              Carreras
	Joseph                                             Castellucio
	Raul                                               Casts
	Matthew                                            Cavallari
	Andrew                                             Cencini
	Stacey                                             Cereghino
	Pat                                                Chambers
	Forrest                                            Chandler
	Lee                                                Chapla
	Yao-Qiang                                          Cheng
	Nicky                                              Chesnut
	Ruth                                               Choin
	Jill                                               Christie
	Alice                                              Clark
	Jane                                               Clayton
	Connie                                             Coffman
	Pat                                                Coleman
	John                                               Colon
	Scott                                              Colvin
	William                                            Conner
	Dorothy                                            Contreras
	Scott                                              Cooper
	Eva                                                Corets
	Marlin                                             Coriell
	Jack                                               Creasey
	Grant                                              Culbertson
	Scott                                              Culp
	Conor                                              Cunningham
	Thierry                                            D'Hers
	Megan                                              Davis
	Alvaro                                             De Matos Miranda Filho
	Jacob                                              Dean
	Alexander                                          Deborde
	Aidan                                              Delaney
	Stefan                                             Delmarco
	Della                                              Demott Jr
	Prashanth                                          Desai
	Bev                                                Desalvo
	Brenda                                             Diaz
	Gabriele                                           Dickmann
	Dick                                               Dievendorff
	Rudolph                                            Dillon
	Blaine                                             Dockter
	Cindy                                              Dodd
	Patricia                                           Doyle
	Gerald                                             Drury
	Reuben                                             D'sa
	Bart                                               Duncan
	Maciej                                             Dusza
	Linda                                              Ecoffey
	Carol                                              Elliott
	Shannon                                            Elliott
	Jauna                                              Elson
	John                                               Emory
	Gail                                               Erickson
	Mark                                               Erickson
	Martha                                             Espinoza
	Twanna                                             Evans
	Ann                                                Evans
	John                                               Evans
	Carolyn                                            Farino
	Geri                                               Farrell
	Rhoda                                              Finley
	Kathie                                             Flood
	Kelly                                              Focht
	Garth                                              Fort
	Dorothy                                            Fox
	Susan                                              French
	Mihail                                             Frintu
	John                                               Ford
	Paul                                               Fulton
	Bob                                                Gage
	Michael                                            Galos
	Jon                                                Ganio
	Kathleen                                           Garza
	Dominic                                            Gash
	Janet                                              Gates
	Orlando                                            Gee
	Darren                                             Gehring
	Jim                                                Geist
	Barbara                                            German
	Leo                                                Giakoumakis
	Frances                                            Giglio
	Janet                                              Gilliat
	Mary                                               Gimmi
	Jeanie                                             Glenn
	Diane                                              Glimp
	Scott                                              Gode
	Mete                                               Goktepe
	Brian                                              Goldstein
	Abigail                                            Gonzalez
	Michael                                            Graff
	Derek                                              Graham
	Jane                                               Greer
	Douglas                                            Groncki
	Brian                                              Groth
	Hattie                                             Haemon
	Erin                                               Hagens
	Betty                                              Haines
	Bryan                                              Hamilton
	Kerim                                              Hanif
	Jean                                               Handley
	Katherine                                          Harding
	Lucy                                               Harrington
	Keith                                              Harris
	Roger                                              Harui
	Ann                                                Hass
	James                                              Haugh
	Brenda                                             Heaney
	John                                               Hanson
	Valerie                                            Hendricks
	Kari                                               Hensien
	Irene                                              Hernandez
	Jésus                                              Hernandez
	Cheryl                                             Herring
	Ronald                                             Heymsfield
	Andrew                                             Hill
	Mike                                               Hines
	Matthew                                            Hink
	Helge                                              Hoeing
	Bob                                                Hodges
	Jean                                               Holloway
	Eddie                                              Holmes
	Juanita                                            Holman
	Peter                                              Houston
	Curtis                                             Howard
	Janice                                             Hows
	George                                             Huckaby
	Joshua                                             Huff
	Arlene                                             Huff
	Phyllis                                            Huntsman
	Lawrence                                           Hurkett
	Ryan                                               Ihrig
	Beth                                               Inghram
	Lucio                                              Iallo
	Richard                                            Irwin
	Erik                                               Ismert
	Denean                                             Ison
	Bronson                                            Jacobs
	Eric                                               Jacobsen
	Jodan                                              Jacobson
	Mary                                               Alexander
	David                                              Jaffe
	Vance                                              Johns
	Stephen                                            Jiang
	Danielle                                           Johnson
	Barry                                              Johnson
	Brian                                              Johnson
	David                                              Johnson
	Jean                                               Jordan
	Peggy                                              Justice
	Diane                                              Krane
	Sandra                                             Kitt
	Sandeep                                            Kaliyath
	Lori                                               Kane
	Kay                                                Krane
	Sandeep                                            Katyal
	Victor                                             Kelley
	John                                               Kelly
	Robert                                             Kelly
	Kevin                                              Kennedy
	Mary                                               Kesslep
	Elizabeth                                          Keyser
	Imtiaz                                             Khan
	Karan                                              Khanna
	Joe                                                Kim
	Shane                                              Kim
	Tim                                                Kim
	Anton                                              Kirilov
	Christian                                          Kleinerman
	Andrew                                             Kobylinski
	Kirk                                               King
	Eugene                                             Kogan
	Scott                                              Konersmann
	Joy                                                Koski
	Mitch                                              Kennedy
	Margaret                                           Krupka
	Deepak                                             Kumar
	Vamsi                                              Kuppa
	Peter                                              Kurniawan
	Eric                                               Lang
	David                                              Lawrence
	Elsa                                               Leavitt
	Michael                                            Lee
	Marjorie                                           Lee
	Mark                                               Lee
	Jolie                                              Lenehan
	Roger                                              Lengel
	A.                                                 Leonetti
	Bonnie                                             Lepro
	Linda                                              Leste
	Elsie                                              Lewin
	George                                             Li
	Yale                                               Li
	Yuhong                                             Li
	Joseph                                             Lique
	Paulo                                              Lisboa
	David                                              Liu
	Jinghao                                            Liu
	Todd                                               Logan
	Sharon                                             Looney
	Anita                                              Lucerne
	Judy                                               Lundahl
	Robert                                             Lyeba
	Robert                                             Lyon
	Denise                                             Maccietto
	Scott                                              MacDonald
	Ajay                                               Manchepalli
	Tomas                                              Manzanares
	Kathy                                              Marcovecchio
	Cecelia                                            Marshall
	Linda                                              Martin
	Frank                                              Martˇnez
	Steve                                              Masters
	Jennifer                                           Maxham
	Chris                                              Maxwell
	Sandra                                             Maynard
	Robin                                              McGuigan
	Lola                                               McCarthy
	Jane                                               McCarty
	James                                              McCoy
	Yvonne                                             McKay
	Nkenge                                             McLin
	Nancy                                              McPhearson
	Raquel                                             Mello
	R. Morgan                                          Mendoza
	Stephen                                            Mew
	Helen                                              Meyer
	Thomas                                             Michaels
	Virginia                                           Miller
	Ben                                                Miller
	Dylan                                              Miller
	Frank                                              Miller
	Neva                                               Mitchell
	Laura                                              Steele
	Shanay                                             Steelman
	Stefano                                            Stefani
	Alan                                               Steiner
	Derik                                              Stenerson
	Wathalee                                           Steuber
	Alice                                              Steiner
	Liza Marie                                         Stevens
	Jim                                                Stewart
	Robert                                             Stotka
	Kayla                                              Stotler
	Ruby Sue                                           Styles
	Gary                                               Suess
	Ruth                                               Suffin
	Elizabeth                                          Sullivan
	Michael                                            Sullivan
	Marcia                                             Sultan
	Brad                                               Sutton
	Abraham                                            Swearengin
	Katherine                                          Swan
	Julie                                              Taft-Rider
	Clarence                                           Tatman
	Mike                                               Taylor
	Chad                                               Tedford
	Vanessa                                            Tench
	Judy                                               Thames
	Phyllis                                            Thomas
	Donald                                             Thompson
	Kendra                                             Thompson
	Daniel                                             Thompson
	Yuping                                             Tian
	Diane                                              Tibbott
	Delia                                              Toone
	Glenn                                              Track
	Billy                                              Trent
	Christie                                           Trujillo
	Phyllis                                            Tuffield
	Sairaj                                             Uddin
	Sunil                                              Uppal
	Esther                                             Valle
	Jessie                                             Valerio
	Rose                                               Vandenouer
	Gregory                                            Vanderbout
	Michael                                            Vanderhyde
	Margaret                                           Vanderkamp
	Kara                                               Vanderlinden
	Nieves                                             Vargas
	Gary                                               Vargas
	Ranjit                                             Varkey Chudukatil
	Patricia                                           Vasquez
	Dora                                               Verdad
	Wanda                                              Vernon
	Robert                                             Vessa
	Caroline                                           Vicknair

	(814 row(s) affected)

*/
